services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'pratik'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'insti'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: